// AUTOGENERATED FROM PICO_CONFIG_HEADER_FILES and then PICO_<PLATFORM>_CONFIG_HEADER_FILES
// DO NOT EDIT!


// based on PICO_CONFIG_HEADER_FILES:

//#include \"${var}\"


// based on PICO_${PICO_PLATFORM_UPPER}_CONFIG_HEADER_FILES:

//#include \"${var}\"

#include <boards/pico.h>
